Feature: [Component:WorkflowGenerator] As a [User:Consumer] I want to call [API:generate_workflow] so that I receive a valid workflow JSON or a handled error. KPI: [KPI:successful workflow generation rate]

  Scenario: [Story:Retrieve existing workflow Happy Path]
    Given the [Input:user_task] is "Analyze market trends" [Function:generate_workflow]
    And the [Component:DatabaseManager] returns one similar workflow record [API:retrieve_similar_workflow]
    When the [Function:generate_workflow] processes the retrieval branch [FunctionComponent:retrieval_logic]
    Then it returns a JSON payload containing the existing workflow under key "main" [Concept:ResultSerialization]
    And the [State:missing_nodes] list is empty [State:missing_nodes]

  Scenario: [Story:New workflow generation with embeddings table missing]
    Given the [Input:user_task] is "Generate monthly report" [Function:generate_workflow]
    And the [Component:DatabaseManager] returns no records [API:retrieve_similar_workflow]
    And invoking [Function:generate_embeddings] raises psycopg2.Error with pgcode '42P01' [Exception:psycopg2.Error]
    When the [Function:generate_workflow] continues despite missing embeddings table [FunctionComponent:embeddings_fallback]
    And it compiles the planning graph via [Function:create_planning_workflow] [Function:create_planning_workflow]
    And it invokes the StateGraph until completion [Component:StateGraph.invoke]
    Then it returns a JSON payload of the newly generated workflow [Concept:WorkflowSerialization]
    And it attempts to save via [API:save_workflow] on [Component:DatabaseManager] [Function:save_workflow]
    And the [State:missing_nodes] list is empty [State:missing_nodes]

  Scenario: [Story:Finalize_missing branch when nodes are missing]
    Given the [Input:user_task] is "Process unknown nodes" [Function:generate_workflow]
    And the [Component:DatabaseManager] returns no records [API:retrieve_similar_workflow]
    And the planning graph invocation sets [State:missing_node_error] to true [State:missing_node_error]
    When the [Component:StateGraph] follows conditional edge to "finalize_missing" [Component:StateGraph]
    Then it returns the initial_state JSON with missing node IDs included [Concept:MissingNodeFallback]
    And the [State:missing_nodes] list contains one or more IDs [State:missing_nodes]

  Scenario: [Story:Invalid input raises ValueError]
    Given the [Input:user_task] is an empty string "" [Function:generate_workflow]
    When the [Function:generate_workflow] validates input [Function:generate_workflow]
    Then it raises a ValueError with message "User task must be a valid non-empty string." [Exception:ValueError]

  Scenario: [Story:Database retrieve error fallback]
    Given the [Input:user_task] is "Check DB error" [Function:generate_workflow]
    And invoking [Function:retrieve_similar] raises WorkflowError due to DB outage [Exception:WorkflowError]
    When the [Function:generate_workflow] handles the retrieval exception [FunctionComponent:retrieval_logic]
    Then it proceeds as if no similar record was found [Concept:RetrievalFallback]
    And it does not raise an exception [State:workflow_continues]

  Scenario: [Story:Save workflow warning on DB save failure]
    Given the [Input:user_task] is "Generate and save" [Function:generate_workflow]
    And no similar workflows exist [API:retrieve_similar_workflow]
    And planning completes with [State:final_workflow] data present [Component:StateGraph.invoke]
    And saving via [API:save_workflow] throws an Exception [Exception:save_workflow]
    When the [Function:generate_workflow] logs a warning and continues [FunctionComponent:save_logic]
    Then it returns the generated JSON payload [Concept:WorkflowSerialization]
    And a warning log entry "Failed to save workflow; continuing" is produced [Concept:Logging]

  Scenario: [Story:Embedding generation non-critical exception fallback]
    Given the [Input:user_task] is "Build pipeline" [Function:generate_workflow]
    And invoking [Function:generate_embeddings] raises a generic Exception [Exception:Exception]
    When the [Function:generate_workflow] continues past embedding errors [FunctionComponent:embeddings_handling]
    Then it compiles the planning graph via [Function:create_planning_workflow] [Function:create_planning_workflow]
    And it returns a workflow JSON payload [Concept:WorkflowSerialization]
    And logs an INFO "Non-critical embedding error; continuing workflow generation" [Concept:Logging]

  Scenario: [Story:Catastrophic planning failure raises WorkflowError]
    Given the [Input:user_task] is "Plan emergency task" [Function:generate_workflow]
    And invoking [Component:StateGraph.invoke] raises a RuntimeError [Exception:RuntimeError]
    When the [Function:generate_workflow] attempts planning [FunctionComponent:planning_invocation]
    Then it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Empty plan finalizes with no workflow data]
    Given the [Input:user_task] is "Empty plan test" [Function:generate_workflow]
    And the [Component:DatabaseManager] returns no records [API:retrieve_similar_workflow]
    And planning produces an empty [State:final_workflow] dictionary [State:final_workflow]
    When the [Function:generate_workflow] completes execution [FunctionComponent:execute_planning]
    Then it logs a WARNING "No workflow data generated after planning" [Concept:Logging]
    And it returns an empty JSON string "" [Concept:ResultSerialization]

  Scenario: [Story:Allowed_nodes preserved on missing nodes path]
    Given the [Input:user_task] is "Filter nodes test" and [Input:allowed_nodes] is ["A","B"] [Function:generate_workflow]
    And the [Component:DatabaseManager] returns no records [API:retrieve_similar_workflow]
    And the planning graph invocation sets [State:missing_node_error] to true [State:missing_node_error]
    When the [Function:generate_workflow] returns fallback JSON [FunctionComponent:missing_node_fallback]
    Then the returned JSON contains "allowed_nodes": ["A","B"] [Concept:ResultSerialization]
    And the [State:missing_nodes] list is non-empty [State:missing_nodes]

  Scenario: [Story:Similar workflow unpacking error fallback]
    Given the [Input:user_task] is "Unpack error test" [Function:generate_workflow]
    And the [Component:DatabaseManager] returns one record with invalid wf_obj unpackable [API:retrieve_similar_workflow]
    When the [Function:generate_workflow] attempts to unpack wf_obj [FunctionComponent:retrieval_logic]
    Then it logs an exception "Error unpacking similar workflow result" [Concept:Logging]
    And it returns "{}" as JSON [Concept:ResultSerialization]

  Scenario: [Story:Transient DB error retry success]
    Given the [Input:user_task] is "Retry DB test" [Function:generate_workflow]
    And the first call to [API:retrieve_similar_workflow] raises psycopg2.OperationalError [Exception:psycopg2.OperationalError]
    And the second call to [API:retrieve_similar_workflow] returns one similar workflow [API:retrieve_similar_workflow]
    When the [Function:generate_workflow] processes the retrieval with retry [FunctionComponent:retrieve_similar]
    Then it returns the existing workflow JSON under "main" [Concept:ResultSerialization]
    And the retry decorator succeeds without propagating errors [Concept:RetryMechanism]

  Scenario: [Story:WorkflowError during planning]
    Given the [Input:user_task] is "Error during planning" [Function:generate_workflow]
    And invoking [Component:StateGraph.invoke] raises WorkflowError [Exception:WorkflowError]
    When the [Function:generate_workflow] handles the exception [FunctionComponent:planning_logic]
    Then it logs an error "Critical error in planning workflow" [Concept:Logging]
    And it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Replan when workflow is invalid]
    Given the [Input:user_task] is "Replan test task" [Function:generate_workflow]
    When the [Function:generate_workflow] processes a state with [State:workflow_valid] set to false [State:workflow_valid]
    Then it follows the "planning" branch in the planning workflow [FunctionComponent:planning_logic]
    And it returns a valid workflow JSON or handled error [Concept:ResultSerialization]

  Scenario: [Story:Catastrophic planning failure during workflow compilation]
    Given the [Input:user_task] is "Catastrophic planning failure test" [Function:generate_workflow]
    When the [Function:create_planning_workflow] raises an exception during compilation [FunctionComponent:planning_workflow]
    Then it logs an error "Failed to compile planning workflow" [Concept:Logging]
    And it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Successful workflow retrieval]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:generate_workflow] finds a similar workflow in the database [FunctionComponent:database_manager]
    Then it returns the existing workflow JSON [Concept:ResultSerialization]

  Scenario: [Story:Node embedding table missing during generation]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:generate_workflow] encounters a missing 'node_embeddings' table error [Exception:psycopg2.Error]
    Then it logs an info message about missing table [Concept:Logging]
    And it continues without raising an error [Concept:ErrorHandling]

  Scenario: [Story:Generic embedding service error]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:generate_workflow] encounters a generic embedding service error [Exception:RuntimeError]
    Then it logs an info message about the error [Concept:Logging]
    And it continues without raising an error [Concept:ErrorHandling]

  Scenario: [Story:Planning workflow failure]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:create_planning_workflow] raises an exception [Exception:RuntimeError]
    Then it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Database error during planning]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:generate_workflow] encounters a psycopg2.Error with code other than '42P01' [Exception:psycopg2.Error]
    Then it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Missing nodes detected]
    Given the [Input:user_task] is "Handle missing nodes" [Function:generate_workflow]
    When the [Function:generate_workflow] detects missing nodes in the final state [State:missing_nodes]
    Then it returns the missing nodes list [Concept:ResultSerialization]

  Scenario: [Story:Final workflow processing error]
    Given the [Input:user_task] is "Trigger final workflow processing error" [Function:generate_workflow]
    When the [Function:generate_workflow] encounters a non-serializable object in final workflow [Exception:TypeError]
    Then it raises a WorkflowError [Exception:WorkflowError]

  Scenario: [Story:Retry transient database errors]
    Given the [Input:user_task] is "Retry DB test" [Function:generate_workflow]
    When the [Function:retrieve_similar] raises transient psycopg2.OperationalError [Exception:psycopg2.OperationalError]
    Then it retries retrieval up to 3 times [Concept:RetryLogic]
    And it eventually returns a workflow or empty result [Concept:ResultSerialization]

  Scenario: [Story:Save workflow non-critical error]
    Given the [Input:user_task] is "task" [Function:generate_workflow]
    When the [Function:save_workflow] raises a non-critical exception [Exception:Exception]
    Then it logs a warning message [Concept:Logging]
    And it continues without raising an error [Concept:ErrorHandling]

  Scenario: [Story:Empty plan finalizes workflow]
    Given the [Input:user_task] is "Empty plan test" [Function:generate_workflow]
    When the [Function:generate_workflow] processes a final workflow with empty plan [State:final_workflow]
    Then it returns None for workflow JSON [Concept:ResultSerialization]

  Scenario: [Story:Allowed nodes preserved]
    Given the [Input:user_task] is "Filter nodes test" [Function:generate_workflow]
    When the [Function:generate_workflow] processes allowed nodes list [State:allowed_nodes]
    Then it returns missing nodes if any [Concept:ResultSerialization]

  Scenario: [Story:Unpacking error fallback]
    Given the [Input:user_task] is "Unpack error test" [Function:generate_workflow]
    When the [Function:generate_workflow] encounters unpacking error [Exception:ValueError]
    Then it returns empty workflow and missing nodes list [Concept:ResultSerialization]

  Scenario: [Story:Performance test]
    Given the [Input:user_task] is "performance test" [Function:generate_workflow]
    When the [Function:generate_workflow] runs under performance constraints [Concept:Performance]
    Then it completes within time limits [Concept:Performance]

  Scenario: [Story:Missing nodes in workflow]
    Given the [Input:user_task] is "Handle missing nodes" [Function:generate_workflow]
    And the planning graph invocation sets [State:missing_node_error] to true [State:missing_node_error]
    When the [Function:generate_workflow] processes the missing nodes [FunctionComponent:missing_node_logic]
    Then it returns a JSON payload with missing nodes [Concept:WorkflowSerialization]
    And the [State:missing_nodes] list contains one or more IDs [State:missing_nodes]

  # NOTE - The nested decide_execute function below is covered by feature scenarios and tests:
  # - Scenario: [Story:Decide execute planning branch] in workflow_generator.feature
  # - Scenario: [Story:Decide execute execute branch] in workflow_generator.feature
  # - Scenario: [Story:Decide execute finalize branch] in workflow_generator.feature
  # However, coverage tools cannot track execution of nested functions properly,
  # so lines in this nested function (lines 505 and 510) appear as uncovered.
  # This is a known limitation of coverage tools with nested/dynamically created functions.

  Scenario: [Story:Decide execute planning branch]
    Given the [Input:user_task] is "Trigger decide_execute planning branch" [Function:generate_workflow]
    When the [Function:generate_workflow] processes a state with workflow_valid set to false [State:workflow_valid]
    Then it follows the "planning" branch in decide_execute function [FunctionComponent:decide_execute]

  Scenario: [Story:Decide execute execute branch]
    Given the [Input:user_task] is "Trigger decide_execute execute branch" [Function:generate_workflow]
    When the [Function:generate_workflow] processes a state with workflow_valid set to true and current_step less than plan length [State:workflow_valid, State:current_step, State:plan]
    Then it follows the "execute" branch in decide_execute function [FunctionComponent:decide_execute]

  Scenario: [Story:Decide execute finalize branch]
    Given the [Input:user_task] is "Empty plan test" [Function:generate_workflow]
    When the [Function:generate_workflow] processes a state with current_step greater or equal to plan length [State:current_step, State:plan]
    Then it follows the "finalize" branch in decide_execute function [FunctionComponent:decide_execute]